### ISSUE TITLE
Correct OrgWise - Organizational Capacity Assessment Tool

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#15]
- [ ] There are many obvious typos in the Organizational Capacity Assessment (OCA):
http://logicaloutcomes.net/forms/index.php/489512
Can you correct most of them in csv and then re-upload the content? If you need to refer to the original content, here's the material - https://usaidlearninglab.org/library/organizational-capacity-assessment

- [ ] The OCA should be split into seven surveys, one for each of 7 domains: governance, finance, administration, human resources, program management, project performance management, and sustainability. Each domain should have its own welcome page (with the nice image). For now, use the same content on each section that is now on the full survey. I will send individual content for each module in a few days. (If you have other suggestions for how to split them I would be interested.)

- [ ] The questions should be numbered. Possibly each section should have a table of contents - is that possible? Does it look okay?

- [ ] The intro section should have better fonts for the headings. E.g., in the following screenshot, the heading and subsection headings are underlined (which should never happen on the web unless they are hyperlinks) and the font seems too small. I will be providing content soon. 

![image](https://cloud.githubusercontent.com/assets/4176201/26607844/68d952d6-4566-11e7-9ce9-2443b7729d86.png)

Your design comments are very welcome.

**Comment by mmirasol** [comment]
@gilliankerr in relation to Review and make recommendations on all OrgWise surveys #17, all the orgwise surveys look complicated because all the question groups are named the same.  It's not clear which of the 7 domains the questions fall under and the questions are repeated with the same answers.  

The questions should first be grouped by area then similar questions should be combined into single questions with subquestions like what we did for the SIS survey.  For ease of navigation in lime, we need to define the subsections and name the groups appropriately.

For example, there are seven areas in the Organizational Capacity Assessment Tool:
1.	Governance and legal structure - GLS
2.	Financial management and internal control systems - FMI
3.	Administration and procurement systems - ADM
4.	Human resources systems - HR
5.	Program management - PM
6.	Project performance management - PPM
7.	Organizational management and sustainability - OMS
so we can name our question groups with these so we can identify which area the group belongs to.

Next there are currently 44 subsections, each with their own descriptions:
1. Vision and Mission - Subsection Objectives:Assess the clarity of the organization
2. Legal Requirements and Status - Subsection Objectives:Determine the organization
3. Organizational Structure - Subsection Objectives:Assess whether the organizational structure is appropriateResources: Organization chart (organogram) or description of the staffing pattern; senior manager and staff questionnaires or interviews
4. Board Composition and Responsibility - Subsection Objectives:Assess the board
5. Succession Planning - Subsection Objectives:Assess the organization
6. Budgeting - Subsection Objectives:Assess the ability to budget and plan financial resourcesResources: Annual and multi-year budgets, financial policies and procedures manuals, financial monitoring tools, revenue and expenditure reports, and financialstaff questionnaires or interviews
7. Accounting System - Subsection Objectives:Assess the ability to record and report revenues and expenditures in an accurate and timely mannerResources: Financial policies and procedures manuals, financial monitoring tools, accounting journals, chart of accounts, general ledger, revenue andexpenditure reports, and financial staff questionnaires or interviews
8. Internal Controls (Checks and Balances and Segregation of Duties) - Subsection Objectives:Assess whether there are adequate internal controls to safeguard funds and check the accuracy and reliability of accounting dataResources: Financial manual, accounting journals, chart of accounts, general ledger, financial statements and annexes, bank records, and financial staff questionnaires or interviews
9. Bank Account Management - Subsection Objectives:Assess whether bank accounts properly separate donor and project funds and personal funds and bank records are properly reconciledand reviewedResources: Financial manual, accounting journals, chart of accounts, general ledger, financial statements and annexes, bank records, and financial staffquestionnaires or interviews
10. Financial Documentation (Financial Records and Filing) - Subsection Objectives:Assess whether the organization has a routine reporting system for financial information and is able to meet various donors
11. Financial Statements and Reporting Subsection Objectives:Assess the policies, procedures, and practices for generating financial statements that meet the needs of the organization and comply with government and donor financial reporting requirementsResources: Financial statements, financial staff questionnaires or interviews
12. Audit Experience Subsection Objectives:Assess whether the organization undergoes routine audits and has a system for addressing audit findings. A key focus of this subsectionis whether existing audit practices meet various donors
13. Cost Sharing Subsection Objectives:Assess whether the organization has systems to track, report, and document cost sharing and meet the cost sharing requirement in theiragreements with various donors
14. Operating Policies, Procedures, and Systems Subsection Objectives:Assess the soundness of operating policies and procedures and the degree of staff understanding and complianceResources: Policy and procedures manual; staff questionnaires; senior manager and staff questionnaires or interviews
15. Information Technology Subsection Objectives:Assess the soundness of IT policies and procedures and systems and staff compliance.Resources: Policy and procedures manual; staff questionnaires; senior manager and staff questionnaires or interviews
16. Travel Policies and Procedures Subsection Objectives:Assess the soundness of travel policies and procedures and degree of staff understanding and complianceResources: Travel procedures manual; travel authorizations and travel vouchers; financial manager, accountant, and staff questionnaires or interviews
17. Procurement Subsection Objectives:Assess the soundness of procurement policies and procedures and degree of staff understanding and complianceResources: Procurement policies, plans, and files; payment vouchers; financial manager, accountant, and staff questionnaires or interviews
18. Fixed Asset Management (Equipment and Property) Subsection Objectives:Assess the soundness of policies and procedures for fixed assets management and degree of staff understanding and compliance.Resources: Fixed assets register, physical inventory reports; payment vouchers: financial manager, accountant, and staff questionnaires or interviews
19. Branding and Marking Subsection Objectives:Assess compliance with the branding and marking requirements of USAID and other donors, where applicableResources: Branding and marking plan; senior manager interviews; observation of signs at project sites, vehicles, equipment, and publications
20. Adequacy of Staffing and Job Descriptions Subsection Objectives:Review the organization
21. Recruitment and Retention Subsection Objectives:Assess the organization
22. Personnel Policies Subsection Objectives:Assess whether the organization
23. Staff Time Management and Payrolls Subsection Objectives:Assess whether the organization has a well-documented payroll system based on accurate timesheets that are signed and approved and reflect hours spent on each project and indirect activitiesResources: Payroll policies and procedures, time sheets, work schedule policies, payment vouchers, timesheets, financial managers and staff questionnaires and interviews
24. Staff and Consultant History Subsection Objectives:Assess whether the organization
25. Staff Salaries and Benefits Subsection Objectives:Assess whether the organization
26. Staff and Contractor Supervision and Work Planning Subsection Objectives:Assess the clarity of supervisory responsibilities and staff and contractor work planningResources: Organization chart, supervision plan, supervisor reports, training needs assessment and training plans for supervisors, employee and contractor workplans, questionnaires or interviews of managers and staff
27. Volunteers and Interns Subsection Objectives:Assess the organization
28. Donor Compliance Requirements Subsection Objectives:Assess the organization
29. Sub-Award(Sub-Grant and Sub-Contract) Management Subsection Objectives:Review systems and procedures for awarding, managing, and supervising sub-grants and sub-contracts to other organizationsResources: Grants manual, sub-grant policies, partner agreements, financial and progress reports from sub-awardees, site visit reports, staff and sub-awardeequestionnaires or interviews
30. Technical Reporting Subsection Objectives:Assess the organization
31. Stakeholder Involvement Subsection Objectives:Assess whether the organization is responsive to stakeholder needs and seeks input from clients (beneficiaries) in designing,implementing, monitoring, and evaluating projectsResources: Project guidelines; stakeholder analyses; project plans; site visit, monitoring, and evaluation reports; client and staff questionnaires or interviews
32. Monitoring and Quality Assurance Subsection Objectives:Review the organization
33. Project and Program Evaluation Subsection Objectives:Review the organization
34. Service Delivery Standards Subsection Objectives:Determine whether the organization has adopted any recognized standards for service delivery and has the ability to apply and monitorthe standards.Resources: International, national, or sectoral standards for service delivery, monitoring reports, evaluations, assessments by standard-setting entities, seniormanager questionnaires and interviews, certifications from organizations assessing standards
35. Field Support, Operations, and Oversight Subsection Objectives:Assess the organization
36. Project Performance (past 3 years) Subsection Objectives:Assess the organization
37. Strategic Planning (Business Planning) Subsection Objectives:Assess the organization
38. Annual Workplans Subsection Objectives:Assess the organization
39. Change Management Subsection Objectives:Assess the organization
40. Knowledge Management and External Linkages Subsection Objectives:Assess the organization
41. Fundraising and New Business Development Subsection Objectives:Assess the organization
42. Internal Communications and Decision Making (within the organization) Subsection Objectives:Assess the effectiveness of the organization
43. External Communications Subsection Objectives:Assess the effectiveness of the organization
44. Advocacy and Influence Subsection Objectives:Assess the strategies and effectiveness of the organization

@gilliankerr can you please identify which area each subsection belongs to.  I will prepare an excel file so you do this easily.

**Comment by gilliankerr** [comment]
@traciwilson Could you identify these areas using the excel file that Mark will provide?

**Comment by mmirasol** [comment]
@gilliankerr can you please review this list and send it back with the correct area assignments.
[section list.zip](https://github.com/LogicalOutcomes/SIS-LimeSurvey/files/1046106/section.list.zip)

**Comment by mmirasol** [comment]
@gilliankerr please see my comments below:

Can you correct most of them in csv and then re-upload the content? If you need to refer to the original content, here's the material - https://usaidlearninglab.org/library/organizational-capacity-assessment
> can correct them faster on the web but i think we need to restructure the survey first.

 The OCA should be split into seven surveys, one for each of 7 domains: governance, finance, administration, human resources, program management, project performance management, and sustainability. Each domain should have its own welcome page (with the nice image). For now, use the same content on each section that is now on the full survey. I will send individual content for each module in a few days. (If you have other suggestions for how to split them I would be interested.)
> if this survey already has all the questions needed, all we need to do is add one more question at the beginning of the survey asking which areas to display.  please see previous comment with regards to grouping the sections in the current survey.  once we have identified which area each section belongs to we can control the display by area.

The questions should be numbered. Possibly each section should have a table of contents - is that possible? Does it look okay?
> a table of contents may not be necessary for display after we restructure the questions and groups.
> but we definitely need to define the survey better in a word doc.
> this will be the basic for creating the questions groups and the questions themselves.
> i think the survey needs to be redone completely.

The intro section should have better fonts for the headings. E.g., in the following screenshot, the heading and subsection headings are underlined (which should never happen on the web unless they are hyperlinks) and the font seems too small. I will be providing content soon.
> i think the survey would look better after the questions are restructured and survey is set to display question by question.  it would also be easier to manage the questions after that.

**Comment by gilliankerr** [comment]
These are excellent recommendations; I agree. I have asked Moiz for this spreadsheet - he generated these questions - and for his advice on how to do this. If he doesn't have it handy, perhaps @traciwilson can do this..? We will know Moiz's response by tomorrow morning.

**Comment by gilliankerr** [comment]
@mmirasol Could you take this task? Traci is busy with the other 4 surveys, and you have a clear idea of what is required. You would be splitting up the questions into the correct 7 divisions by referring to the source document, adding Traci's introductory text on each survey, fixing typos. Is that okay? We need to complete it by Monday, and the interviews are starting Tuesday. Let me know if that's a problem.

**Comment by mmirasol** [comment]
@gilliankerr yes i will be happy to fix all the text and regroup all the questions. 

I created_ a copy of the current survey and i can proceed with making changes to those.  I see tracy made the same recommendations as i did the other regarding the groupings on the other 4 surveys.  

Do you still wish to create 7 separate surveys or just use one main survey with an initial question asking which areas to show to control the logic?

**Comment by mmirasol** [comment]
@gilliankerr i started working on the text changes. my first few comments on this.  please open the sheet attached and go to the Review tab to go thru my comments.
[Organizational Capacity Survey (293 Question & Thier Answers) - 20170603.01.xlsx](https://github.com/LogicalOutcomes/SIS-LimeSurvey/files/1049431/Organizational.Capacity.Survey.293.Question.Thier.Answers.-.20170603.01.xlsx)

This is how we used to collaborate on survey specs. We have the specs on an easy to read document.  This one is much easier to read than the lime export and named with a date and serial number to track how many times it has been changed and also to exchange comments on the document directly.

**Comment by mmirasol** [comment]
or perhaps it might be better to discuss the issues here directly. here are the first few.

1. There are questions that have the exact same answers as the one before them. Questions should match their answers and it looks like this should be one question split into two.
![image](https://cloud.githubusercontent.com/assets/13954274/26751580/77218e92-486f-11e7-9e66-52e7308e2974.png)
![image](https://cloud.githubusercontent.com/assets/13954274/26751590/a483fc26-486f-11e7-8705-381563e4dc3c.png)
![image](https://cloud.githubusercontent.com/assets/13954274/26751593/ad88377e-486f-11e7-8b65-8cc524b27a6f.png)

**Comment by mmirasol** [comment]
2. There are questions with wrong answer text.
![image](https://cloud.githubusercontent.com/assets/13954274/26751597/dcdd73f4-486f-11e7-8a25-42a122ea33cc.png)
The text in the spec document have them in multiple lines but these would look better as straight sentences.  See below for reference.
![image](https://cloud.githubusercontent.com/assets/13954274/26751606/fdf56dc6-486f-11e7-9282-3b2ee50f9cc1.png)

**Comment by mmirasol** [comment]
This question has two options named "The accounting system is cash based".
![image](https://cloud.githubusercontent.com/assets/13954274/26751921/0f9a2fe2-4877-11e7-8f7c-bc9cefe1d2cb.png)

**Comment by mmirasol** [comment]
This one has two options for "The accounting system is computerized".
![image](https://cloud.githubusercontent.com/assets/13954274/26751933/50fe30c8-4877-11e7-9e34-9cee7c244145.png)

**Comment by mmirasol** [comment]
This question does not answer when the chart of accounts was last updated and the second answer is repeated 3 times.
![image](https://cloud.githubusercontent.com/assets/13954274/26751973/02b95522-4878-11e7-80b7-b7475a26e41e.png)

**Comment by mmirasol** [comment]
This one has duplicate options too.
![image](https://cloud.githubusercontent.com/assets/13954274/26752079/86c1fc0a-487a-11e7-8e28-e18698b9e916.png)

**Comment by mmirasol** [comment]
The answers don't match this question.
![image](https://cloud.githubusercontent.com/assets/13954274/26752106/dfb26d72-487a-11e7-8cde-d199be6cf64f.png)

**Comment by mmirasol** [comment]
The answers are not appropriate for this question.
![image](https://cloud.githubusercontent.com/assets/13954274/26752164/6e79a1d2-487c-11e7-9e0a-52f8ae5f33bf.png)

**Comment by mmirasol** [comment]
Duplicate options for this question too.
![image](https://cloud.githubusercontent.com/assets/13954274/26752235/acede954-487d-11e7-8426-72ada0c8e8a0.png)

**Comment by mmirasol** [comment]
The first two options for this question look the same to me.  Please advise.
![image](https://cloud.githubusercontent.com/assets/13954274/26752329/0b215856-4880-11e7-9d90-e1e76e18c1cc.png)

**Comment by mmirasol** [comment]
The answers do not match this question.
![image](https://cloud.githubusercontent.com/assets/13954274/26752396/6d0426ba-4881-11e7-813f-d2d0ab70d735.png)

**Comment by mmirasol** [comment]
As of this writing, i have correction the question text for 11/45 question groups.  Have to pause temporarily to rest a bit.  I'm also at 19/20 hours this week.  Please add 10 more hours for this week and I will resume working on the text corrections after dinner tonight.

**Comment by mmirasol** [comment]
In case you would like to review, the corrected OCA survey is the inactive one.  
![image](https://cloud.githubusercontent.com/assets/13954274/26752437/3dd7d340-4882-11e7-8fd6-9e4241a245b3.png)

**Comment by mmirasol** [comment]
Also, instead of displaying all the questions in the same group in one page, I would recommend doing it question by question and instead of displaying the group description, add in a boilerplate (display) question at the start of the group to show the objectives and instructions for that group.

For example, show the text below before showing the first question for that group.
Vision and Mission
Objective: Assess the clarity of the organization’s statements of its purpose and values and how they have been shared and applied.
Before completing this section, please refer to your organization’s: Vision statement; mission statement; and board, senior manager, and staff questionnaires or interviews

**Comment by gilliankerr** [comment]
@mmirasol when you see errors or duplications in the questions, flag them for @traciwilson to review. Traci can go back to the original source and check for accuracy.

**Comment by gilliankerr** [comment]
Other than errors and questions in the text, what other issues are outstanding? You and I can discuss them before I leave the house (in about 40 minutes); then I will be unavailable until evening.

**Comment by traciwilson** [comment]
@mmirasol what is the best way to communicate changes/corrections to you after I review? When you see issues such as the text didn't come through in the limesurvey, and you have the full text in the source document, I would suggest just fixing on the spot, rather than creating an issue log for it. This removes several steps of work.
Also, if you'd like to set me up with user permissions, I can make changes or corrections directly as I review them. Thanks!

**Comment by gilliankerr** [comment]
I set you up with user permissions on limesurvey ; let me know if you have any problems with it

**Comment by mmirasol** [comment]
hi @gilliankerr @traciwilson sorry for the wait. had to drive late last night. got ko'd.

**Comment by mmirasol** [comment]
all the issues in text that can be fixed are already fixed actually.  the issues i have posted here are the ones with options that don't make sense. i posted the issues directly on this log so you didn't have to look at the source document but we can do that also so you have full reference.

@traciwilson please look at the file below and use the review feature of excel to look at my comments so you can put in your own.
[Organizational Capacity Survey (293 Question & Thier Answers) - 20170603.01.xlsx](https://github.com/LogicalOutcomes/SIS-LimeSurvey/files/1049957/Organizational.Capacity.Survey.293.Question.Thier.Answers.-.20170603.01.xlsx)



@gilliankerr traci and i won't be able to work on this simultaneously because we are doing imports to replace the text so only one person can work on it.

**Comment by mmirasol** [comment]
@traciwilson i suggest you continue to put your corrections on the file and edit each of the comments i posted above so i can get the corrections for each one directly. i will edit the comments here so you can copy the text directly and search for question on the file.

**Comment by mmirasol** [comment]
Actually you can search for the beginning part of the questions in excel.  See example below.
![image](https://cloud.githubusercontent.com/assets/13954274/26757273/a6a97240-48e9-11e7-89d4-c32a35b75fdd.png)
![image](https://cloud.githubusercontent.com/assets/13954274/26757274/aeecb322-48e9-11e7-9154-7fa93686acab.png)
allows you to find the question with text "Does the organization have an external board of directors that is independent of management.." quickly.  I would suggest you put in the corrections here directly so that we don't have to send files back and forth.

**Comment by mmirasol** [comment]
@gilliankerr @traciwilson i should be done with the first 3/7 areas within the next hour. I will importing these as separate surveys so tracy can test them and put in the correct descriptions for the groups.

**Comment by mmirasol** [comment]
@traciwilson i think the answers need rephrasing.
![image](https://cloud.githubusercontent.com/assets/13954274/26757920/d4f99ec0-48ff-11e7-8b1f-63742a36a65f.png)

**Comment by mmirasol** [comment]
@traciwilson @gilliankerr you can start making corrections to these surveys directly.

Governance and legal structure
http://logicaloutcomes.net/forms/index.php/admin/survey/sa/view/surveyid/235289
test link: http://logicaloutcomes.net/forms/index.php/235289?newtest=Y

Financial management and internal control systems 
http://logicaloutcomes.net/forms/index.php/admin/survey/sa/view/surveyid/345769
test link: http://logicaloutcomes.net/forms/index.php/345769?newtest=Y

Administration and procurement systems 
http://logicaloutcomes.net/forms/index.php/admin/survey/sa/view/surveyid/139821
test link: http://logicaloutcomes.net/forms/index.php/139821?newtest=Y

**Comment by mmirasol** [comment]
@traciwilson please confirm if you were able to login to lime and see the surveys mentioned.
i cannot check your login because @gilliankerr created it.  but i can create a new one for you if needed.  let me know if you need guidance in navigating lime and testing surveys.

**Comment by mmirasol** [comment]
@traciwilson these two questions have the same answers.

![image](https://cloud.githubusercontent.com/assets/13954274/26791825/e58f36c2-4a4a-11e7-9ead-c3bcdf2a4e2a.png)

![image](https://cloud.githubusercontent.com/assets/13954274/26791834/ef05ce28-4a4a-11e7-9d96-d5c1d7d10e26.png)

**Comment by mmirasol** [comment]
thanks @traciwilson can you start putting in the survey intros and section intros?

**Comment by mmirasol** [comment]
@traciwilson these two questions should probably be combined too.

![image](https://cloud.githubusercontent.com/assets/13954274/26800563/5ad74c3c-4a6c-11e7-9fc6-2e88a6800bf0.png)

![image](https://cloud.githubusercontent.com/assets/13954274/26800571/611c8256-4a6c-11e7-9f42-46b4be9364df.png)

**Comment by mmirasol** [comment]
@traciwilson i think these questions should be combined.

![image](https://cloud.githubusercontent.com/assets/13954274/26803728/d8b976c4-4a77-11e7-8888-1591f2ca5cda.png)

![image](https://cloud.githubusercontent.com/assets/13954274/26803735/e162e378-4a77-11e7-92b5-d9963afaec51.png)

**Comment by mmirasol** [comment]
hi @traciwilson great job with the intros. can you help me with:
1. all the corrections above? should be easy to find in the 3 surveys now because they are organized better.
2. the end message of the surveys.  the end page content are in google sites.

ex. https://sites.google.com/view/orgwise/understanding-your-results/governance-and-legal-structure?authuser=0
which says,

Understanding your results
In future phases, OrgWise will be able to score your results and provide a summary. For now, you look at your own responses and save them in pdf by clicking the link below:

Print your results - do not include this text, instead turn on the survey setting for "Participants may print answers".
![image](https://cloud.githubusercontent.com/assets/13954274/26804332/2dc8af48-4a7a-11e7-8f1c-c30f741b18ff.png)

Following is some additional information about this module and how to use the results. 
Achieving your mission and vision
The results of this survey can be compared against benchmark scores of strong capacity. Each question is potentially scored from 1 to 4: low capacity (1), basic capacity (2), moderate capacity (3), and strong capacity (4). For any area where your organization had a low score, review the question answers to identify the next level of capacity that you can aim for. This will assist with prioritization and action planning. 

Once the items above are done, we're done with the first 3 surveys.
We will do the same with the last 4.

**Comment by mmirasol** [comment]
@traciwilson The options don't sound right for this question.

![image](https://cloud.githubusercontent.com/assets/13954274/26804688/79058fac-4a7b-11e7-8abc-10007e8c8995.png)

**Comment by mmirasol** [comment]
@traciwilson The answers don't sound right for this question.

![image](https://cloud.githubusercontent.com/assets/13954274/26805954/0cd603e2-4a81-11e7-9959-8213f1dd023d.png)

**Comment by mmirasol** [comment]
@traciwilson the answers don't answer the questions being asked.

![image](https://cloud.githubusercontent.com/assets/13954274/26806049/81a1736e-4a81-11e7-9d85-3656f89bad0a.png)

**Comment by mmirasol** [comment]
@traciwilson even this one doesn't sound right.

![image](https://cloud.githubusercontent.com/assets/13954274/26806114/c0dece1e-4a81-11e7-852a-57509ced03c8.png)

will put in,
Employee benefits are not documented in a policy manual or handbook given to all employees
Employee benefits are documented in a policy manual or handbook given to all employees

**Comment by mmirasol** [comment]
@traciwilson These two questions should be combined too.

![image](https://cloud.githubusercontent.com/assets/13954274/26806349/f04b8d3a-4a82-11e7-91e2-422992b55b8c.png)

![image](https://cloud.githubusercontent.com/assets/13954274/26806354/fc4e02fc-4a82-11e7-9159-31530bfdc218.png)

**Comment by mmirasol** [comment]
@traciwilson I think these two questions should be combined.

![image](https://cloud.githubusercontent.com/assets/13954274/26807250/0435de68-4a88-11e7-84c9-1f6c63dfd9f2.png)

![image](https://cloud.githubusercontent.com/assets/13954274/26807254/0daf1d7e-4a88-11e7-8410-dbcfb21c9fe3.png)

**Comment by mmirasol** [comment]
These questions should be combined too.
![image](https://cloud.githubusercontent.com/assets/13954274/26807405/d5686924-4a88-11e7-8fe1-089b57ad906b.png)

![image](https://cloud.githubusercontent.com/assets/13954274/26807416/e3d8ab0e-4a88-11e7-8c0f-53973b498108.png)

**Comment by mmirasol** [comment]
@traciwilson @gilliankerr the question does not seem to match the provided answers for these questions.  Please advise.

![image](https://user-images.githubusercontent.com/13954274/26852624-727441bc-4b41-11e7-8a49-c0004a3dd123.png)

![image](https://user-images.githubusercontent.com/13954274/26852635-7ac06cf6-4b41-11e7-98df-4f4d412ce71a.png)

**Comment by mmirasol** [comment]
@gilliankerr these questions would look better as likert scale, will convert them after i split the last 3.

![image](https://user-images.githubusercontent.com/13954274/26854084-2fbb2a92-4b47-11e7-80c2-e5a4c6d5f4b5.png)

**Comment by mmirasol** [comment]
Hi @traciwilson please put in the intros and end page settings for these surveys,

Program management
http://logicaloutcomes.net/forms/index.php/admin/survey/sa/view/surveyid/223922
test link: http://logicaloutcomes.net/forms/index.php/223922?newtest=Y

**Comment by traciwilson** [comment]
Here is a list of questions that I've removed from Program management module, Donor compliance subsection:

Deleted: Has the organization received a direct award from USAID?

Modified: Has the organization received a direct award from donors with complex compliance requirements?. Modified answers to remove mention of USAID.

Modified: Does the head office consistently comply with complex requirements of donors? - removed USAID from question and answers.

Modified: Does the organization have a good understanding of any relevant cost principles? [was USG cost principles]

(additional USAID-specific questions were changed to relevance = 0 so they would not appear in the survey)

**Comment by mmirasol** [comment]
@gilliankerr here are links of our 11 modules.

1. Effective managers
http://logicaloutcomes.net/forms/index.php/154199?newtest=Y

2.  Effective teams 
http://logicaloutcomes.net/forms/index.php/837344?newtest=Y

3. Working in partnership with other organizations 
http://logicaloutcomes.net/forms/index.php/484266?newtest=Y

4. Building community capacity 
http://logicaloutcomes.net/forms/index.php/577829?newtest=Y

5. Governance and legal structure 
http://logicaloutcomes.net/forms/index.php/235289?newtest=Y

6. Financial management and internal control systems
http://logicaloutcomes.net/forms/index.php/345769?newtest=Y

7. Administration and procurement systems 
http://logicaloutcomes.net/forms/index.php/154199?newtest=Y

8. Human resource systems 
http://logicaloutcomes.net/forms/index.php/386626?newtest=Y

9. Program management 
http://logicaloutcomes.net/forms/index.php/223922?newtest=Y

10.  Project performance management 
http://logicaloutcomes.net/forms/index.php/193817?newtest=Y

11. Organizational management and sustainability 
http://logicaloutcomes.net/forms/index.php/114118?newtest=Y

**Comment by mmirasol** [comment]
@gilliankerr all posted issues have been addressed as of this writing.
