### ISSUE TITLE
Make edits on 3 OrgWise surveys

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#16]
Upload the corrected content for 3 surveys in attached file (each survey is on a separate tab) - let me know if you disagree or have problems with any of them.

[Orgwise Surveys Edits AR-GK.xlsx](https://github.com/LogicalOutcomes/SIS-LimeSurvey/files/1042371/Orgwise.Surveys.Edits.AR-GK.xlsx)

**Comment by gilliankerr** [comment]
Hold on this; I think there are errors in the spreadsheet.

**Comment by mmirasol** [comment]
Hi @gilliankerr in the future please use comments to identify changes.
![image](https://cloud.githubusercontent.com/assets/13954274/26687513/780b1772-4722-11e7-93fa-a1ecb31556b1.png)

Also, this format is very hard to read and review.  You have to click on each cell to see what's in each one.
I would suggest using a word document instead for better readability and to use the review option in word / excel to place comments so that when we send changes it's easy to go to those changes directly without having to read the whole document each time.

**Comment by mmirasol** [comment]
Recreating the surveys from .txt does not include the advanced settings so it breaks the formatting of the questions.  See the left and right labels are not displayed correctly.
![image](https://cloud.githubusercontent.com/assets/13954274/26690828/641059de-472d-11e7-8fb1-ebfb265d6f85.png)

In addition, people can remove html tags that make the question look better see the first page does not look good.
![image](https://cloud.githubusercontent.com/assets/13954274/26690809/5050a930-472d-11e7-8a3b-d65b2a722c36.png)

**Comment by mmirasol** [comment]
Best practice would to get to the final report would be to let people apply the text directly and test to make sure the question was done well.

**Comment by mmirasol** [comment]
stopped working on this as per @gilliankerr advise. restored and reactivated the old surveys.
