### ISSUE TITLE
Correct number of questions in Manager Feedback Survey

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#23]
In the intro page, it says there are 3 questions but there are actually 11. 
Correct that number
![image](https://user-images.githubusercontent.com/4176201/26836828-ea7b39d8-4aa9-11e7-9c98-c2ba06f8367a.png)

**Comment by traciwilson** [comment]
@gilliankerr Done. The number of questions was an auto-populated field which counted the number of questions, but due to how the questions are set up in lime, it considered each grouping as 1 question. I've manually entered "11" as the number of questions, so if the survey ever changes, we'll need to manually update the intro page as well,
